apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
spec:
  source:
    repoURL: https://github.com/my-org/my-helm-chart
    path: charts/my-app
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: my-namespace
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
